### ISSUE TITLE
Very helpful, but confused about a detail

### ISSUE THREAD

**Issue by Parth** [beryx-gist/badass-jlink-example-kotlin-javafx#2]
My project didn't seem to work until I followed the launcher pattern. Could you explain what's going on under the hood?

https://github.com/lockbook/lockbook-dev-desktop/

is the project in question

**Comment by siordache** [comment]
This is a "feature" of the LauncherHelper provided by openjdk: 
[If the main class extends javafx.application.Application](https://github.com/unofficial-openjdk/openjdk/blob/d304c03b8a60da31e4124a9c54d9cee8f0d3a4ba/src/java.base/share/classes/sun/launcher/LauncherHelper.java#L668-L673), LauncherHelper calls the `setFXLaunchParameters` method, which [checks if the javafx.graphics module is present](https://github.com/unofficial-openjdk/openjdk/blob/d304c03b8a60da31e4124a9c54d9cee8f0d3a4ba/src/java.base/share/classes/sun/launcher/LauncherHelper.java#L994-L998). This check fails in a non-modular application. 

As [discussed here](http://mail.openjdk.java.net/pipermail/openjfx-dev/2018-June/021977.html), the workaround is to have a separate main class that doesn't extend javafx.application.Application. 

It seems that there are no plans to change the behavior of LauncherHelper, because, as Kevin Rushforth says in the above mentioned thread: _"effort would be better spent getting everything to work with javafx.* modules as proper named modules"_.

**Comment by Parth** [comment]
Thanks, I'll read through all of this and close.
